/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  quests: [{type: 'autogenerated', dirName: 'quests'}],
  certification: [{type: 'autogenerated', dirName: 'certification'}],
  resources: [{type: 'autogenerated', dirName: 'resources'}],
  about: [{type: 'autogenerated', dirName: 'about'}],
  contribute: [{type: 'autogenerated', dirName: 'contribute'}],
  sponsor: [{type: 'autogenerated', dirName: 'sponsor'}],
};

module.exports = sidebars;
